<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import { Download, Edit3, Plus, RefreshCw, Save, Search, ShieldCheck, Trash2, Upload, X } from "lucide-vue-next";
import { apiRequest, errorMessage } from "../shared/api";
import { deriveExtensionSummary, parseKeyValueLines } from "./model";

type Tab = "overview" | "skills" | "mcp" | "tools" | "catalog";
const tabs: Array<{ id: Tab; label: string }> = [
  { id: "overview", label: "总览" }, { id: "skills", label: "技能" }, { id: "mcp", label: "MCP 服务" },
  { id: "tools", label: "工具目录" }, { id: "catalog", label: "在线扩展" },
];
const state = reactive({ skills: [] as any[], servers: [] as any[], tools: [] as any[] });
const activeTab = ref<Tab>("overview");
const busy = ref(false); const message = ref(""); const messageError = ref(false); const toolFilter = ref("");
const drawer = ref<HTMLDialogElement | null>(null); const drawerKind = ref<"skill" | "mcp">("skill");
const uploadInput = ref<HTMLInputElement | null>(null); const catalogDialog = ref<HTMLDialogElement | null>(null);
const catalog = ref<any[]>([]); const catalogStale = ref(false); const catalogQuery = ref(""); const catalogKind = ref("all"); const selectedCatalog = ref<any>(null);
const skillTools = ref<any[]>([]); const editingSkill = ref<string | null>(null);
const skillForm = reactive({ name: "", description: "", instructions: "", prompt_hint: "", tool_names: [] as string[] });
const mcpForm = reactive({ name: "", description: "", transport: "stdio", command: "", args: "", env: "", url: "", headers: "" });
const summary = computed(() => deriveExtensionSummary(state));
const visibleTools = computed(() => { const q = toolFilter.value.trim().toLowerCase(); return state.tools.filter((tool) => !q || [tool.name, tool.server, tool.description].some((v) => String(v || "").toLowerCase().includes(q))); });
const visibleCatalog = computed(() => { const q = catalogQuery.value.trim().toLowerCase(); return catalog.value.filter((item) => !q || [item.id, item.name, item.description, ...(item.categories || [])].join(" ").toLowerCase().includes(q)); });
const skillGroups = computed(() => Object.entries(state.skills.reduce((groups: Record<string, any[]>, skill) => { const key = skill.metadata?.category || "其他"; (groups[key] ||= []).push(skill); return groups; }, {})).sort(([a], [b]) => a.localeCompare(b, "zh")));
let pollTimer = 0;

function notify(text: string, isError = false) { message.value = text; messageError.value = isError; }
async function refreshAll(silent = false) {
  if (!silent) busy.value = true;
  try {
    const [skills, servers, tools, availableTools] = await Promise.all([
      apiRequest<any[]>("/api/skills"), apiRequest<any[]>("/api/mcp/servers"), apiRequest<any[]>("/api/mcp/tools"), apiRequest<any[]>("/api/skills/tools"),
    ]);
    state.skills = skills; state.servers = servers; state.tools = tools; skillTools.value = availableTools;
    if (!silent) notify("扩展状态已刷新");
  } catch (reason) { notify(errorMessage(reason), true); }
  finally { busy.value = false; }
}
function startPolling() { stopPolling(); pollTimer = window.setInterval(() => refreshAll(true), 30000); }
function stopPolling() { if (pollTimer) window.clearInterval(pollTimer); pollTimer = 0; }
async function showPage() { await refreshAll(true); startPolling(); }

function resetSkill() { editingSkill.value = null; Object.assign(skillForm, { name: "", description: "", instructions: "", prompt_hint: "", tool_names: [] }); }
function openSkill(skill?: any) { resetSkill(); drawerKind.value = "skill"; if (skill) { editingSkill.value = skill.name; Object.assign(skillForm, { name: skill.name, description: skill.description || "", instructions: skill.instructions || "", prompt_hint: skill.prompt_hint || "", tool_names: [...(skill.tool_names || [])] }); } nextTick(() => drawer.value?.showModal()); }
function openMcp() { drawerKind.value = "mcp"; Object.assign(mcpForm, { name: "", description: "", transport: "stdio", command: "", args: "", env: "", url: "", headers: "" }); nextTick(() => drawer.value?.showModal()); }
async function saveSkill() {
  if (!skillForm.name.trim() || !skillForm.instructions.trim()) return notify("名称与提示词不能为空", true);
  busy.value = true;
  try {
    const body = { description: skillForm.description.trim(), instructions: skillForm.instructions.trim(), prompt_hint: skillForm.prompt_hint.trim(), tool_names: skillForm.tool_names };
    if (editingSkill.value) await apiRequest(`/api/skills/${encodeURIComponent(editingSkill.value)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    else await apiRequest("/api/skills", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: skillForm.name.trim(), ...body }) });
    drawer.value?.close(); await refreshAll(true); notify(editingSkill.value ? "技能修改已保存" : "技能已创建");
  } catch (reason) { notify(errorMessage(reason), true); } finally { busy.value = false; }
}
async function patchSkill(skill: any, patch: Record<string, unknown>) { try { await apiRequest(`/api/skills/${encodeURIComponent(skill.name)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); await refreshAll(true); notify("技能状态已更新"); } catch (reason) { notify(errorMessage(reason), true); } }
async function removeSkill(skill: any) { if (!confirm(`删除技能 ${skill.name}？`)) return; try { await apiRequest(`/api/skills/${encodeURIComponent(skill.name)}`, { method: "DELETE" }); await refreshAll(true); notify("技能已删除"); } catch (reason) { notify(errorMessage(reason), true); } }
async function uploadSkill(file?: File) { if (!file) return; const body = new FormData(); body.append("file", file); try { const result: any = await apiRequest("/api/skills/upload", { method: "POST", body }); await refreshAll(true); notify(result.installed?.length ? `已安装：${result.installed.join("、")}` : "上传完成"); } catch (reason) { notify(errorMessage(reason), true); } finally { if (uploadInput.value) uploadInput.value.value = ""; } }

async function saveMcp() {
  if (!mcpForm.name.trim()) return notify("服务器名称不能为空", true);
  try { await apiRequest("/api/mcp/servers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: mcpForm.name.trim(), description: mcpForm.description.trim(), transport: mcpForm.transport, command: mcpForm.command.trim(), args: mcpForm.args.split(/\r?\n/).map(v => v.trim()).filter(Boolean), env: parseKeyValueLines(mcpForm.env), url: mcpForm.url.trim(), headers: parseKeyValueLines(mcpForm.headers), enabled: true }) }); drawer.value?.close(); await refreshAll(true); notify("MCP 服务已保存并连接"); } catch (reason) { notify(errorMessage(reason), true); }
}
async function toggleMcp(server: any) { try { await apiRequest(`/api/mcp/servers/${encodeURIComponent(server.name)}/${server.enabled ? "disable" : "enable"}`, { method: "POST" }); await refreshAll(true); } catch (reason) { notify(errorMessage(reason), true); } }
async function testMcp(server: any) { notify(`正在测试 ${server.name}…`); try { const result: any = await apiRequest(`/api/mcp/servers/${encodeURIComponent(server.name)}/test`, { method: "POST" }); notify(result.ok ? `${server.name} 连接正常：${result.tool_count} 个工具，耗时 ${result.elapsed_ms}ms` : `${server.name} 连接失败：${result.error}`, !result.ok); await refreshAll(true); } catch (reason) { notify(errorMessage(reason), true); } }
async function saveGrants(server: any, event: Event) { const value = (event.target as HTMLInputElement).value; const ids = value.split(",").map(v => v.trim()).filter(Boolean); try { await apiRequest(`/api/mcp/servers/${encodeURIComponent(server.name)}/grants`, { method: "PATCH", headers: { "Content-Type": "application/json", "X-YUMENO-Request": "web" }, body: JSON.stringify({ allowed_persona_ids: ids }) }); notify(`已更新 ${server.name} 的授权`); } catch (reason) { notify(errorMessage(reason), true); } }
async function removeMcp(server: any) { if (!confirm(`删除 MCP 服务器 ${server.name}？其工具将立即不可用。`)) return; try { await apiRequest(`/api/mcp/servers/${encodeURIComponent(server.name)}`, { method: "DELETE" }); await refreshAll(true); notify("MCP 服务已删除"); } catch (reason) { notify(errorMessage(reason), true); } }

async function loadCatalog(refresh = false) { try { const snapshot: any = await apiRequest(`/api/extensions/catalog?kind=${encodeURIComponent(catalogKind.value)}${refresh ? "&refresh=true" : ""}`); catalog.value = snapshot.items || []; catalogStale.value = Boolean(snapshot.stale); } catch { notify("在线扩展目录暂时不可用，可稍后重试", true); catalog.value = []; } }
function isInstalled(item: any) { return item.kind === "skill" ? state.skills.some(v => v.name === item.id) : state.servers.some(v => v.name === item.id); }
function openCatalog(item: any) { selectedCatalog.value = item; nextTick(() => catalogDialog.value?.showModal()); }
async function installCatalog() { const item = selectedCatalog.value; if (!item) return; try { const preview: any = await apiRequest(`/api/extensions/catalog/${encodeURIComponent(item.id)}/install`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmed: false }) }); if (preview.preview?.conflicts?.length) throw new Error(preview.preview.conflicts.join("；")); const result: any = await apiRequest(`/api/extensions/catalog/${encodeURIComponent(item.id)}/install`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmed: true }) }); if (result.status !== "installed") throw new Error(result.message || "安装未完成"); await refreshAll(true); catalogDialog.value?.close(); notify(item.kind === "skill" ? "安装完成，请在技能页启用并信任" : "安装完成，请在 MCP 页启用并授权角色"); } catch (reason) { notify(errorMessage(reason), true); } }

onMounted(() => { const root = document.querySelector("#extensions-app-root"); root?.addEventListener("yumeno:extensions-show", showPage); root?.addEventListener("yumeno:extensions-hide", stopPolling); showPage(); });
onBeforeUnmount(() => stopPolling());
</script>

<template>
  <main class="yv-page extension-page">
    <header class="extension-hero"><div><span class="yv-kicker">Agent capability registry</span><h1>能力扩展</h1><p>统一管理角色可调用的 Skill、Tool 与 MCP 服务。</p></div><div class="hero-actions"><span :class="['yv-status', summary.attentionCount ? 'warn' : 'ok']">{{ summary.attentionCount ? `${summary.attentionCount} 项待处理` : '运行正常' }}</span><button class="yv-button yv-icon-button" title="刷新" :disabled="busy" @click="refreshAll()"><RefreshCw /></button></div></header>
    <section class="signal-strip" aria-label="能力状态"><div><span>已启用技能</span><strong>{{ summary.enabledSkills }}</strong><small>共 {{ state.skills.length }} 个</small></div><div><span>MCP 在线</span><strong>{{ summary.mcpOnline }}</strong><small>{{ summary.mcpIssues }} 项异常</small></div><div><span>已注册工具</span><strong>{{ summary.toolCount }}</strong><small>统一工具注册表</small></div><div><span>需要处理</span><strong>{{ summary.attentionCount }}</strong><small>信任与连接状态</small></div></section>
    <nav class="extension-tabs"><button v-for="tab in tabs" :key="tab.id" :class="{ active: activeTab === tab.id }" @click="activeTab = tab.id; tab.id === 'catalog' && loadCatalog(false)">{{ tab.label }}</button></nav>
    <p v-if="message" :class="['extension-message', { error: messageError }]" role="status">{{ message }}</p>

    <section v-if="activeTab === 'overview'" class="overview-layout"><div class="capability-line"><article><span>决策层</span><strong>Agent</strong><p>选择是否调用扩展能力</p></article><article class="skill"><span>指令层</span><strong>Skill</strong><p>按场景注入执行规则</p></article><article class="tool"><span>执行层</span><strong>Tool</strong><p>标准化系统动作</p></article><article class="mcp"><span>协议层</span><strong>MCP</strong><p>连接外部工具服务</p></article></div><div class="overview-foot"><div><h2>当前连接</h2><p v-if="!state.servers.length" class="yv-empty">尚未配置 MCP 服务</p><div v-for="server in state.servers" :key="server.name" class="health-row"><strong>{{ server.name }}</strong><span>{{ server.description || '外部工具服务' }}</span><em :class="['yv-status', server.status?.status === 'connected' ? 'ok' : 'warn']">{{ server.status?.status === 'connected' ? `${server.status.tool_count} 个工具` : server.status?.status === 'error' ? '连接异常' : '未连接' }}</em></div></div><div class="quick-entry"><h2>管理入口</h2><button class="yv-button primary" @click="openSkill()"><Plus />新增技能</button><button class="yv-button" @click="openMcp()"><Plus />新增 MCP 服务</button></div></div></section>

    <section v-else-if="activeTab === 'skills'" class="content-section"><header><div><span class="yv-kicker">Instruction packages</span><h2>技能</h2><p>为 Agent 提供按需加载的规则与工具组合。</p></div><div><input ref="uploadInput" hidden type="file" accept=".zip" @change="uploadSkill(($event.target as HTMLInputElement).files?.[0])"><button class="yv-button" @click="uploadInput?.click()"><Upload />上传技能包</button><button class="yv-button primary" @click="openSkill()"><Plus />新增技能</button></div></header><div v-if="!state.skills.length" class="yv-empty">还没有技能</div><section v-for="[group, skills] in skillGroups" :key="group" class="skill-group"><h3>{{ group }}</h3><article v-for="skill in skills" :key="skill.name" class="extension-row kind-skill"><div class="row-main"><div><strong>{{ skill.name }}</strong><span>{{ skill.builtin ? '内置' : '自定义' }} · {{ skill.format === 'skillmd' ? '标准包' : 'JSON' }}</span></div><p>{{ skill.description || '暂无说明' }}</p><div class="tag-line"><span v-for="tool in skill.tool_names" :key="tool">{{ tool }}</span></div></div><div class="row-actions"><span :class="['yv-status', skill.enabled ? 'ok' : 'warn']">{{ skill.enabled ? '已启用' : '已停用' }}</span><button class="yv-button yv-icon-button" :title="skill.enabled ? '停用' : '启用'" @click="patchSkill(skill, { enabled: !skill.enabled })"><ShieldCheck /></button><button v-if="!skill.builtin && !skill.trusted" class="yv-button" @click="patchSkill(skill, { trusted: true })">信任</button><button v-if="!skill.builtin" class="yv-button yv-icon-button" title="编辑" @click="openSkill(skill)"><Edit3 /></button><button v-if="!skill.builtin" class="yv-button yv-icon-button danger" title="删除" @click="removeSkill(skill)"><Trash2 /></button></div></article></section></section>

    <section v-else-if="activeTab === 'mcp'" class="content-section"><header><div><span class="yv-kicker">External protocol services</span><h2>MCP 服务</h2><p>连接、测试并限制外部服务可访问的角色。</p></div><button class="yv-button primary" @click="openMcp()"><Plus />新增服务</button></header><div v-if="!state.servers.length" class="yv-empty">尚未配置 MCP 服务</div><article v-for="server in state.servers" :key="server.name" class="extension-row kind-mcp"><div class="row-main"><div><strong>{{ server.name }}</strong><span>{{ server.transport }} · {{ server.enabled ? '已启用' : '已停用' }}</span></div><p>{{ server.description || server.status?.error || '暂无说明' }}</p><label class="grant-field"><span>授权角色</span><input :value="(server.allowed_persona_ids || []).join(',')" placeholder="* 或角色 ID，逗号分隔" @change="saveGrants(server, $event)"></label></div><div class="row-actions"><span :class="['yv-status', server.status?.status === 'connected' ? 'ok' : server.status?.status === 'error' ? 'error' : 'warn']">{{ server.status?.status === 'connected' ? `${server.status.tool_count} 个工具` : server.status?.status === 'error' ? '连接失败' : '等待连接' }}</span><button class="yv-button" @click="testMcp(server)">测试</button><button class="yv-button" @click="toggleMcp(server)">{{ server.enabled ? '停用' : '启用' }}</button><button class="yv-button yv-icon-button danger" title="删除" @click="removeMcp(server)"><Trash2 /></button></div></article></section>

    <section v-else-if="activeTab === 'tools'" class="content-section"><header><div><span class="yv-kicker">Unified registry</span><h2>工具目录</h2><p>查看内置工具与 MCP 工具的统一注册结果。</p></div><label class="filter-input"><Search /><input v-model="toolFilter" placeholder="搜索工具名、服务或描述"></label></header><div v-if="!visibleTools.length" class="yv-empty">没有匹配的工具</div><article v-for="tool in visibleTools" :key="`${tool.server}/${tool.name}`" class="extension-row kind-tool"><div class="row-main"><div><strong>{{ tool.name }}</strong><span>{{ tool.server || '内置' }}</span></div><p>{{ tool.description || '暂无说明' }}</p></div><span :class="['yv-status', tool.requires_confirmation ? 'warn' : 'ok']">{{ tool.requires_confirmation ? '调用需确认' : '可直接调用' }}</span></article></section>

    <section v-else class="content-section"><header><div><span class="yv-kicker">Curated catalog</span><h2>在线扩展</h2><p>先检查来源与权限，再将扩展加入本地能力系统。</p></div><button class="yv-button" @click="loadCatalog(true)"><RefreshCw />刷新目录</button></header><div class="catalog-tools"><label class="filter-input"><Search /><input v-model="catalogQuery" placeholder="搜索名称、说明或分类"></label><select v-model="catalogKind" @change="loadCatalog(false)"><option value="all">全部类型</option><option value="skill">Skill</option><option value="mcp">MCP</option></select><span :class="['yv-status', catalogStale ? 'warn' : 'ok']">{{ catalogStale ? '缓存目录' : `${catalog.length} 个条目` }}</span></div><div class="catalog-grid"><article v-for="item in visibleCatalog" :key="item.id" :class="['catalog-item', `kind-${item.kind}`]"><span>{{ item.kind.toUpperCase() }}</span><h3>{{ item.name || item.id }}</h3><small>v{{ item.version || '未知' }} · {{ item.id }}</small><p>{{ item.description || '暂无说明' }}</p><div class="tag-line"><span v-for="tag in item.categories" :key="tag">{{ tag }}</span></div><button class="yv-button" :disabled="isInstalled(item)" @click="openCatalog(item)">{{ isInstalled(item) ? '已安装' : '查看并安装' }}</button></article></div></section>

    <dialog ref="drawer" class="yv-dialog"><header class="dialog-head"><div><span class="yv-kicker">{{ drawerKind === 'skill' ? 'Instruction package' : 'Protocol service' }}</span><h2>{{ drawerKind === 'skill' ? (editingSkill ? `编辑 ${editingSkill}` : '新增技能') : '新增 MCP 服务' }}</h2></div><button class="yv-button yv-icon-button" title="关闭" @click="drawer?.close()"><X /></button></header><form v-if="drawerKind === 'skill'" class="dialog-body" @submit.prevent="saveSkill"><label class="yv-field"><span>名称</span><input v-model="skillForm.name" :readonly="!!editingSkill"></label><label class="yv-field"><span>描述</span><input v-model="skillForm.description"></label><label class="yv-field"><span>提示词</span><textarea v-model="skillForm.instructions" rows="6"></textarea></label><label class="yv-field"><span>触发提示</span><input v-model="skillForm.prompt_hint"></label><fieldset class="tool-options"><legend>可附加工具</legend><label v-for="tool in skillTools" :key="tool.name"><input v-model="skillForm.tool_names" type="checkbox" :value="tool.name"><span>{{ tool.name }}{{ tool.requires_confirmation ? '（需确认）' : '' }}</span></label></fieldset><button class="yv-button primary" type="submit"><Save />保存技能</button></form><form v-else class="dialog-body" @submit.prevent="saveMcp"><label class="yv-field"><span>名称</span><input v-model="mcpForm.name"></label><label class="yv-field"><span>描述</span><input v-model="mcpForm.description"></label><div class="transport-tabs"><button v-for="item in [{id:'stdio',label:'本地进程'},{id:'streamable_http',label:'远程 HTTP'},{id:'sse',label:'远程 SSE'}]" :key="item.id" type="button" :class="{ active: mcpForm.transport === item.id }" @click="mcpForm.transport = item.id">{{ item.label }}</button></div><template v-if="mcpForm.transport === 'stdio'"><label class="yv-field"><span>启动命令</span><input v-model="mcpForm.command"></label><label class="yv-field"><span>参数（每行一个）</span><textarea v-model="mcpForm.args" rows="3"></textarea></label><label class="yv-field"><span>环境变量（KEY=VALUE）</span><textarea v-model="mcpForm.env" rows="3"></textarea></label></template><template v-else><label class="yv-field"><span>服务器地址</span><input v-model="mcpForm.url"></label><label class="yv-field"><span>请求头（KEY: VALUE）</span><textarea v-model="mcpForm.headers" rows="3"></textarea></label></template><button class="yv-button primary" type="submit"><Save />保存服务</button></form></dialog>
    <dialog ref="catalogDialog" class="yv-dialog"><header class="dialog-head"><div><span class="yv-kicker">安装预览</span><h2>{{ selectedCatalog?.name || selectedCatalog?.id }}</h2></div><button class="yv-button yv-icon-button" title="关闭" @click="catalogDialog?.close()"><X /></button></header><div class="dialog-body"><p>{{ selectedCatalog?.description || '暂无说明' }}</p><dl class="catalog-detail"><dt>类型</dt><dd>{{ selectedCatalog?.kind?.toUpperCase() }}</dd><dt>版本</dt><dd>{{ selectedCatalog?.version || '未知' }}</dd><dt>来源</dt><dd>{{ selectedCatalog?.source?.type || '未知' }}</dd></dl><button class="yv-button primary" @click="installCatalog"><Download />确认安装</button></div></dialog>
  </main>
</template>
